[2023-04-08T10:09:46.680+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T16:30:00+00:00 [queued]>
[2023-04-08T10:09:50.649+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T16:30:00+00:00 [queued]>
[2023-04-08T10:09:50.682+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:09:50.700+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 3
[2023-04-08T10:09:50.721+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:09:54.807+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 16:30:00+00:00
[2023-04-08T10:09:56.087+0000] {standard_task_runner.py:55} INFO - Started process 13447 to run task
[2023-04-08T10:09:55.573+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T16:30:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-04-08T10:09:56.172+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T16:30:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-04-08T10:09:57.570+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T16:30:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmp0f9qrssk']
[2023-04-08T10:09:57.746+0000] {standard_task_runner.py:83} INFO - Job 266: Subtask say_Hi
[2023-04-08T10:09:57.993+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-08T10:10:05.497+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T16:30:00+00:00 [running]> on host cfece00ff772
[2023-04-08T10:10:17.712+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=say_Hi
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T16:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-06T16:30:00+00:00
[2023-04-08T10:10:19.543+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-08T10:10:19.695+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Doing Hi in Italian!!"']
[2023-04-08T10:10:24.532+0000] {subprocess.py:86} INFO - Output:
[2023-04-08T10:10:25.242+0000] {subprocess.py:93} INFO - Doing Hi in Italian!!
[2023-04-08T10:10:25.258+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-04-08T10:10:32.649+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=say_Hi, execution_date=20230406T163000, start_date=20230408T100947, end_date=20230408T101032
[2023-04-08T10:10:36.665+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-08T10:10:40.074+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
