[2023-04-06T03:11:13.230+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_simple_dag.greet manual__2023-04-06T03:11:08.472654+00:00 [queued]>
[2023-04-06T03:11:13.244+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_simple_dag.greet manual__2023-04-06T03:11:08.472654+00:00 [queued]>
[2023-04-06T03:11:13.246+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T03:11:13.247+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-06T03:11:13.249+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T03:11:13.271+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2023-04-06 03:11:08.472654+00:00
[2023-04-06T03:11:13.278+0000] {standard_task_runner.py:55} INFO - Started process 210 to run task
[2023-04-06T03:11:13.282+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_simple_dag', 'greet', 'manual__2023-04-06T03:11:08.472654+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpub5ik07a']
[2023-04-06T03:11:13.287+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask greet
[2023-04-06T03:11:13.509+0000] {task_command.py:389} INFO - Running <TaskInstance: my_simple_dag.greet manual__2023-04-06T03:11:08.472654+00:00 [running]> on host cfece00ff772
[2023-04-06T03:11:13.735+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_simple_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T03:11:08.472654+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-06T03:11:08.472654+00:00
[2023-04-06T03:11:13.743+0000] {logging_mixin.py:137} INFO - Writing in file
[2023-04-06T03:11:13.746+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ciao.py", line 10, in greet
    with open('/Development/airflow_tutorial/greet.txt', 'a+', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Development/airflow_tutorial/greet.txt'
[2023-04-06T03:11:13.780+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=my_simple_dag, task_id=greet, execution_date=20230406T031108, start_date=20230406T031113, end_date=20230406T031113
[2023-04-06T03:11:13.813+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task greet ([Errno 2] No such file or directory: '/Development/airflow_tutorial/greet.txt'; 210)
[2023-04-06T03:11:13.861+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-06T03:11:13.924+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
