[2023-04-08T07:09:19.680+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-04-08T07:09:19.635365+00:00 and task will be retried at 2023-04-08T07:11:51.789612+00:00.
[2023-04-08T07:09:21.983+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-08T10:12:07.998+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [queued]>
[2023-04-08T10:12:08.851+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [queued]>
[2023-04-08T10:12:08.863+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:12:08.872+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 3
[2023-04-08T10:12:08.889+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:12:11.123+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 12:10:00+00:00
[2023-04-08T10:12:11.590+0000] {standard_task_runner.py:55} INFO - Started process 13505 to run task
[2023-04-08T10:12:13.552+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T12:10:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmp0urxgfji']
[2023-04-08T10:12:13.687+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask say_Hi
[2023-04-08T10:12:20.361+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:10:00+00:00 [running]> on host cfece00ff772
[2023-04-08T10:12:30.419+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=say_Hi
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T12:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-06T12:10:00+00:00
[2023-04-08T10:12:31.876+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-08T10:12:32.465+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Doing Hi in Italian!!"']
[2023-04-08T10:12:37.110+0000] {subprocess.py:86} INFO - Output:
[2023-04-08T10:12:37.403+0000] {subprocess.py:93} INFO - Doing Hi in Italian!!
[2023-04-08T10:12:37.410+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-04-08T10:12:42.619+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=say_Hi, execution_date=20230406T121000, start_date=20230408T101208, end_date=20230408T101242
[2023-04-08T10:12:45.903+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-08T10:12:51.253+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
