[2023-04-08T07:07:01.587+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:40:00+00:00 [up_for_retry]> on host cfece00ff772
[2023-04-08T07:09:20.637+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:40:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-04-08T07:09:20.636793+00:00 and task will be retried at 2023-04-08T07:11:53.783579+00:00.
[2023-04-08T07:09:21.119+0000] {local_task_job.py:151} INFO - Task is not able to be run
[2023-04-08T10:13:26.035+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:40:00+00:00 [queued]>
[2023-04-08T10:13:28.589+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:40:00+00:00 [queued]>
[2023-04-08T10:13:28.629+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:13:28.663+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 3
[2023-04-08T10:13:28.755+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:13:32.143+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): say_Hi> on 2023-04-06 12:40:00+00:00
[2023-04-08T10:13:35.185+0000] {standard_task_runner.py:55} INFO - Started process 13546 to run task
[2023-04-08T10:13:36.194+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'say_Hi', 'scheduled__2023-04-06T12:40:00+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpndru0kcb']
[2023-04-08T10:13:38.050+0000] {standard_task_runner.py:83} INFO - Job 278: Subtask say_Hi
[2023-04-08T10:13:55.041+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.say_Hi scheduled__2023-04-06T12:40:00+00:00 [running]> on host cfece00ff772
[2023-04-08T10:14:12.137+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=say_Hi
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T12:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-06T12:40:00+00:00
[2023-04-08T10:14:13.381+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-08T10:14:13.579+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "Doing Hi in Italian!!"']
[2023-04-08T10:14:16.381+0000] {subprocess.py:86} INFO - Output:
[2023-04-08T10:14:16.756+0000] {subprocess.py:93} INFO - Doing Hi in Italian!!
[2023-04-08T10:14:16.763+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-04-08T10:14:18.164+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=say_Hi, execution_date=20230406T124000, start_date=20230408T101326, end_date=20230408T101418
[2023-04-08T10:14:27.018+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-08T10:14:48.462+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
